name: CI
on: [push]
jobs:
  build:
    name: Build and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        env:
          TOKEN_FOR_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2
        env:
          TOKEN_FOR_GITHUB: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: yarn build
        env:
          TOKEN_FOR_GITHUB: ${{ secrets.GITHUB_TOKEN }}
