name: Publish package to GitHub Packages
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Bump version
        run: |
          YARN_VERSION_GIT_TAG='' yarn version --patch
          NEW_VERSION=${{ github.event.release.tag_name }}
          if [ -z $NEW_VERSION ]; then
            NEW_VERSION=${{ github.event.inputs.version }}
          fi
          echo "::set-output name=version::$NEW_VERSION"

      - name: Pull Remote Changes
        run: git pull --autostash

      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit & Push
        with:
          commit_message: Bumped version to ${{ steps.bump-version.outputs.version }}"

      - uses: actions/setup-node@v3
        name: Set up node
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true

      - name: Install dependencies
        run: yarn install
        env:
          TOKEN_FOR_GITHUB: ${{ secrets.GITHUB_TOKEN }}

      - run: yarn build && yarn publish
        name: Build and publish
        env:
          TOKEN_FOR_GITHUB: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
