name: Publish package to npm

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update version
        run: |
          export NEW_VERSION=${{ github.event.release.tag_name }}
          if [ -z $NEW_VERSION ]; then
            export NEW_VERSION=${{ github.event.inputs.version }}
          fi

          yarn version --new-version $NEW_VERSION

      - name: Pull Remote Changes
        run: git pull --autostash

      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit & Push
        with:
          commit_message: Updated version to $NEW_VERSION

      - uses: actions/setup-node@v3
        name: Set up node
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true

      - name: Install dependencies
        run: yarn install

      - name: Build and publish
        run: yarn build && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
