name: Publish package to npm

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update version
        run: |
          export NEW_VERSION=${{ github.event.release.tag_name }}
          if [ -z $NEW_VERSION ]; then
            export NEW_VERSION=${{ github.event.inputs.version }}
          fi

          git config --global user.email "bot@terran.one"
          git config --global user.name "Github Bot"

          yarn version --new-version $NEW_VERSION
          git pull --autostash
          git push

      - uses: actions/setup-node@v3
        name: Set up node
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org' # set up .npmrc file to publish to npm

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
